version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: innovationsv
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: api
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - postgres

volumes:
  pgdata:
